- hosts: haproxy
  become: true
  vars:
    haproxy_backend_servers:
      - name: vm-01
        address: 192.168.0.233:80
      - name: vm-02
        address: 192.168.0.13:80
      - name: vm-03
        address: 192.168.0.156:80
  roles:
   - geerlingguy.haproxy

- hosts: all
  become: true
  roles:
   - gusevvs
